[package]
name = "rubocop-daemon-wrapper"
version = "0.1.0"
authors = ["Dave Goddard <dave@goddard.id.au>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'

[dependencies]
fs2 = "*"
which = "*"
tempdir = "*"
scopeguard = "*"
